export const REQUEST_TODO_LIST = 'REQUEST_TODO_LIST';
export const SUCCESS_TODO_LIST = 'SUCCESS_TODO_LIST';
export const FAILURE_TODO_LIST = 'FAILURE_TODO_LIST';

export const ADD_TODO = 'ADD_TODO';
export const SUCCESS_ADD_TODO = 'SUCCESS_ADD_TODO';

export const UPDATE_TODO = 'UPDATE_TODO';
export const SUCCESS_UPDATE_TODO = 'SUCCESS_UPDATE_TODO';

export const REMOVE_TODO = 'REMOVE_TODO';
export const SUCCESS_REMOVE_TODO = 'SUCCESS_REMOVE_TODO';
